spring.application.name=demo
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3304/springRED
spring.datasource.username=springRED
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.configuration.maximum-pool-size=30
app.datasource.url=jdbc:mysql://localhost:3304/springRED
app.datasource.username=springRED
app.datasource.password=
app.datasource.max-total=30